#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: CI

# Triggers the workflow on push only for the main branch
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: "Checkout workspace-data-sync source code"
      uses: actions/checkout@v2
    - name: "Docker prepare"
      run: docker image prune -a -f
    - name: "Docker quay.io Login"
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: "Run build script"
      run:  ./build.sh --tag next
    - name: "Docker Push"
      run: |
       SHORT_SHA1=$(git rev-parse --short HEAD)
       docker tag quay.io/eclipse/che-workspace-data-sync-storage:next quay.io/eclipse/che-workspace-data-sync-storage:${SHORT_SHA1}
       docker tag quay.io/eclipse/che-sidecar-workspace-data-sync:next quay.io/eclipse/che-sidecar-workspace-data-sync:${SHORT_SHA1}
       docker push quay.io/eclipse/che-workspace-data-sync-storage:${SHORT_SHA1}
       docker push quay.io/eclipse/che-sidecar-workspace-data-sync:${SHORT_SHA1}
       docker push quay.io/eclipse/che-workspace-data-sync-storage:next
       docker push quay.io/eclipse/che-sidecar-workspace-data-sync:next

    - name: "Docker Logout"
      run: docker logout
