#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: RELEASE
# Triggers the workflow on push  to the release branch
on:
  push:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: "Checkout workspace-data-sync source code"
      uses: actions/checkout@v3
    - name: "Docker prepare"
      run: docker image prune -a -f
    - name: "Docker quay.io Login"
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: "Run build script"
      run:  ./build.sh
    - name: "Run release script: push images to the quay.io and create tag on GitHub"
      run:  ./release.sh
    - name: "Docker Logout"
      run: docker logout
