#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: RELEASE
# Triggers the workflow on push  to the release branch
on:
  push:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout workspace-data-sync source code"
      uses: actions/checkout@v2
    - name: "Docker prepare"
      run: docker image prune -a -f
    - name: "Docker Quay.io Login"
      run:  docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
    - name: "Run build script"
      run:  ./build.sh
    - name: "Run release on GitHub script"
      run:  ./release_git.sh 
      